- hosts: backend
  become: true
  gather_facts: yes
  tasks:
    - name: "git clone be from github"
      command: "chdir=/home/dody git clone git@github.com:djatmico4/wayhsub-backend.git"
    
    - name: "rename directory to be backend"
      command: "chdir=/home/dody mv wayshub-backend backend"
    
    - name: "create image backend"
      command: "chdir=/home/dody/backend docker build -t djatmico/backend ."

    - name: "run container backend"
      command: "chdir=/home/dody/backend docker-compose up -d"