- hosts: database
  become: true
  gather_facts: yes
  tasks:
    - name: "create new user"
      user: 
        name: dody
        password: $6$NSuNdjQzyDBdGY$FjyceQ0EFUIQT2IancQqmjLPFrCCmppeWgNla.KdSuW7cx3tZTrFjXpQmx85SpQV2p2ORjyQMEgmFEweh0Yd2/
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        group: sudo
        shell: /bin/bash
        createhome: yes
        home: /home/dody
    
- hosts: database
  become: true
  gather_facts: yes
  tasks:
    - name: "change config sshd_config to use password"
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: 'PasswordAuthentication no'
        line: PasswordAuthentication yes
    
    - name: "enable password authentication"
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '#PubkeyAuthentication yes'
        line: PubkeyAuthentication yes
    
    - name: "restart systemd sshd"
      systemd:
        name: sshd
        state: restarted