- hosts: backend
  become: true
  gather_facts: yes
  tasks:
    - name: "run postgresql"
      command: docker run -d --name postgre -v /home/dody/postgres:/var/lib/postgresql/data -e POSTRGRES_PASSWORD=dody123 -p 5432:5432 postgres --restart unless-stopped postgre