- hosts: docker
  become: true
  become_user: dody
  gather_facts: yes
  tasks:
     - name: "install requirements"
       apt:
          name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

#     - name: "install docker repo"
#       shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
#       args:
#          executable: /bin/bash

#     - name: "install docker repo"
#       shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
#       args:
#          executable: /bin/bash

     - name: "update system"
       apt:
          update_cache: yes

     - name: "install docker"
       apt:
          name:
          - docker-ce
          - docker-ce-cli
          - containerd.io