- hosts: nginx
  become: true
  gather_facts: yes
  tasks:
     - name: "update system"
       apt:
        update_cache: yes
     
     - name: "upgrade system"
       apt:
        upgrade: dist

     - name: "install nginx"
       apt:
          name: nginx
          state: latest
          
     