- hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: "install node exporter"
      command: "docker run -d --name=node-exporter --net=\"host\" --pid=\"host\" -v \"/:/host:ro,rslave\" prom/node-exporter:latest --path.rootfs=/host"