- hosts: Monitoring
  become: true
  gather_facts: yes
  tasks:
    - name: "copy configuration prometheus.yml"
      copy:
        src: config/
        dest: /home/dody/prometheus/
        owner: dody
        group: sudo
        mode: 0664
    - name: "install prometheus"
      command: "docker run -d --name=prometheus -p 9090:9090 -v /home/dody/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus"
    - name: "install grafana"
      command: "docker run -d --name=grafana -p 3000:3000 grafana/grafana"
