global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus_metrics'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter_metrics'
    scrape_interval: 5s
    static_configs:
      #node-exporter
    - targets: ['10.111.45.84:9100', '10.111.45.49:9100', '10.111.45.70:9100', '10.111.45.133:9100', '10.111.45.239:9100']