global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'prometheus_metrics'
    scrape_interval: 5s
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node_exporter_metrics'
    scrape_interval: 5s
    static_configs:
      #node-exporter
    - targets: ['10.111.45.146:9100', '10.111.45.90:9100', '10.111.45.158:9100', '10.111.45.159:9100']